### ISSUE TITLE
$watch not handled when select image

### ISSUE THREAD

**Issue by daruwanov** [thenikso/angular-cloudinary#4]
Hello! I am trying to use your library. Showing images works fine. But i have some issue with upload images to cloudinary. Can you help me with this? 

1) i use this your directive https://gist.github.com/thenikso/8899bc6b760e094dd2b5
2) and than in my controller i try do this (from your example)

``` javascript
$scope.$watch('somePhoto', function(myFile) {
    console.log("112233");
    // Use the service to upload the file
    //cloudinary.upload(myFile, { /* cloudinary options here */ })
    // This returns a promise that can be used for result handling
    //.then(function (resp) {
      //alert('all done!');
    //});
  });
```

I try output the console log in watch... by any result..

3) in view i have next 

``` html
<input type="file" ng-model="somePhoto">
```

**Comment by thenikso** [comment]
this looks more like a problem with your scope setup. You probably are in an isolated scope. try to call it `ctrl.somePhoto`. 

I'm closing since it is not related to angular-cloudinary at all
